# Generated by Django 3.2.7 on 2021-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('review', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('property_long', models.CharField(max_length=36)),
                ('property', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('ENT', 'ENT'), ('PRR', 'PRR'), ('HTR', 'HTR'), ('SHR', 'SHR')], max_length=36)),
                ('accomodates', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0.0)),
                ('beds', models.IntegerField(default=0)),
                ('number_of_baths', models.DecimalField(decimal_places=1, max_digits=5)),
                ('bathroom_shared', models.BooleanField(default=True)),
                ('amenities', models.TextField()),
                ('price_eu', models.IntegerField(default=0)),
                ('price_us', models.IntegerField(default=0)),
                ('listing_url', models.URLField(max_length=80)),
                ('picture_url', models.URLField()),
            ],
        ),
    ]
