# Generated by Django 3.2.7 on 2021-10-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='accomodates',
            new_name='accommodates',
        ),
    ]
