# Generated by Django 3.2.7 on 2021-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbs', '0002_rename_accomodates_accommodation_accommodates'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='neighbourhood',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
