# Generated by Django 3.2.7 on 2021-10-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbs', '0003_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
