# Generated by Django 3.2.7 on 2021-10-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbs', '0003_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='bathroom_shared',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
